### ISSUE TITLE
TA comments

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI-532-Group108#52]
Hello,
Thanks for your submission of milestone 01. The submission was very clear and structured. I just have some comments for improvement below.
- In your teamwork contract, you need to include the general roles and responsibilities of each team member and the procedure by which new tasks are introduced and assigned.
- It is not clear if the user can select multiple neighborhoods to show the crimes per year chart.
- In your proposal, I think another research question your app will be able to answer is regarding the change in crimes by time not just if someone wants to know the current state of crimes in the city.

Finally as a general note: make sure to collaborate effectively and equally by commiting using informative messages and create issues for communications.

Thanks!

**Comment by dkruszew** [comment]
See reflection.md for resolutions
