### ISSUE TITLE
Feedback on Vancouver Crime stats

### ISSUE THREAD

**Issue by zouwenjiao** [UBC-MDS/DSCI-532-Group108#65]
1. The loading speed is really slow and it looks like nothing has changed whether I choose a different dropdown option or time span.

2. It will be better to show the name of each neighborhood on the map.

3. There is no introduction or instruction about the website's functionality.

4. There is no tooltip in the line chart.

5. Briefly explain what the crime index max is.

**Comment by dkruszew** [comment]
See reflection.md for summary of these issues and resolutions
