### ISSUE TITLE
Inter-team Feedback

### ISSUE THREAD

**Issue by camadi** [UBC-MDS/DSCI-532-Group108#66]
1. Add Multiselect option for two or more neighbourhoods but not ALL.
2. Rename Crime Index Max to something more understandable. Also please optimize code to improve the speed
3. Rename x label of line plot for weekly rate instead of the column name. 
4. Time scaler: does it average weeks and months or does it randomly display information from a random week/month?

**Comment by dkruszew** [comment]
See reflection.md for summary of these issues and resolutions
