### ISSUE TITLE
Feedback (Braden & Andrés)

### ISSUE THREAD

**Issue by AndresPitta** [UBC-MDS/DSCI-532-Group108#67]
- The size of the charts is making the plots hard to visualize
- Sliders and dropdowns do not work or work slowly.
- Labels on dropdowns should be changed.
- Format of the labels in Neighbourhood charts can be changed to the format of the variables
- The max index normalization is a little bit confusing at first and it needs further explanation to be understood.
- Idea: The max index bar needs a small explanation somewhere in the dashboards
- Idea: Having a ranking variable can also be helpful

**Comment by dkruszew** [comment]
See reflection.md for summary of these issues and resolutions
