### ISSUE TITLE
TA comments on milestone 2

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/DSCI-532-Group108#69]
Hello,

Thank you for your submission of milestone 2. I am sure that you put a lot of effort into producing the app and its documentation. I see that you are always commiting and using pull requests, but try to add an extended description of the commits that you find a little vague. You also use issues for communication and task assignment, but I see that team members tend not to comment on issues.

Regarding the app, I like how you use a mix of geographic,line plots for visualizations. I have some suggestions for the app that I will be listing below.
- It is always required for an online visualization tool to have a description of the app at the beginning. 
- I suggest using a different color scale for the map, as it is pretty hard to see the difference between different levels of GDP with this color scale. 
- You should include or cite the data source.
- You have used some interactive features which I find very helpful for users.
- Finally, I like your reflection you did every thing that was required in this task

**Comment by dkruszew** [comment]
See reflection.md for summary of these issues and resolutions
